### ISSUE TITLE
Add basic information to README

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj.github.io#13]
The README should include at least the following:
- An overview of what this repository is (e.g. Github pages site using Jekyll)
- How to build and test locally
- How to contribute

**Comment by msgilligan** [comment]
PR #51 addresses most of this issue (except the "how to build and test locally" part.)

**Comment by schildbach** [comment]
Shall we close this then?

**Comment by msgilligan** [comment]
I was going to hold out until we added documentation for  "how to build and test locally", but not that you ask I'll go ahead and close it.
