### ISSUE TITLE
maven builds are no longer supported

### ISSUE THREAD

**Issue by systemsplanet** [bitcoinj/bitcoinj.github.io#32]
[page](https://bitcoinj.github.io/using-maven)

**Comment by schildbach** [comment]
You can still use Maven, even if you depend on master. Maven and Gradle are compatible when it comes to the pom.xml and the build artifacts.

**Comment by schildbach** [comment]
Although there is no `pom.xml` in the project itself any more, you can still deploy to a Maven repository which creates a basic `pom.xml` on the fly. And in fact, we'll do that when we will be releasing current master as version 0.15.x. So the instructions on the page you linked to should still be valid, even in future.

**Comment by systemsplanet** [comment]
Might want to add instructions for people who download the zip expecting it will build as a maven project. It wont until the poms are added back.


Also, I noticed the maven-enforcer-plugin is missing from the gradle build, but maybe that's a different issue.

**Comment by schildbach** [comment]
The switch from maven to gradle for building will be covered in the 0.15 changelog, which I agree we can start writing down already.

I tried finding a substitute for the dependency pinning, but could not find any. And also I think pinning should be done by the "app" (the project that builds the final artifacts that are shipped to the end user, e.g. APK).
