### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [bitcoinj/bitcoinj.github.io#42]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@schildbach: No it is not a duplicate:
- https://github.com/bitcoinj/bitcoinj.github.io/search?q=spongycastle&unscoped_q=spongycastle

**Comment by schildbach** [comment]
You're refering to an old JavaDoc. Please look at the current version: https://github.com/bitcoinj/bitcoinj.github.io/tree/ccf1a8f740ebc35f95e64e8ec2ef337ac86bd957/javadoc/0.14.7
