### ISSUE TITLE
Provide link to Issues DB on Google Code

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj.github.io#8]
When viewing the website, It's not easy to find the Issues Database on Google Code.

**Comment by msgilligan** [comment]
My suggestion is to add a "Resources" section and put the link there (it also works for #9) Another option is to include it in the community section. Let me know...

**Comment by mikehearn** [comment]
Maybe both? Otherwise resources section is easiest. We could also have a simple horizontal set of icons using an icon font for github, bugs, mail.

**Comment by msgilligan** [comment]
Looking at it more closely it makes sense to put both new links in the "Community" section (so Nav at top of page doesn't have to change and a new section for only 2 links that both arguably belong in Community seems unnecessary)

**Comment by msgilligan** [comment]
PR #12 was merged. Closing.
